Repository nhs-r-community/statements-on-tools, pull requests merged in 2023-07, with the labels that each got.

#64 Made changes to vision
  nhsr-vision.qmd
Labels: content

#66 Fix eval
  docs/index.html
  docs/nhs-r-vision.html
  docs/open-code.html
  docs/search_index.json
  r-info.qmd
Labels: bug

#67 GitHub action
  .github/workflows/quarto-publish.yml
  _quarto.yml
  r-info.qmd
Labels: bug, content

#68 switches to using renv
  .Rprofile
  .github/workflows/quarto-publish.yml
  renv.lock
Labels: bug

#70 R info
  r-info.qmd
  statement-on-using-tools.qmd
Labels: content

#71 Renamed r-info to technical-r
  _quarto.yml
  technical-r.qmd
Labels: bug

#75 Added alt text and links to image urls
  statement-on-using-tools.qmd
Labels: content

#76 Moved glossary to appendix
  _quarto.yml
Labels: content

#78 Added contributing instructions
  _quarto.yml
  contribution.qmd
Labels: content

#79 Added Python and Git holding chapters
  _quarto.yml
  statement-on-using-tools-git.qmd
  statement-on-using-tools-python.qmd
  statement-on-using-tools-r.qmd
Labels: content
